/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/life/home',
    component: 'layout.blank$view.home',
    meta: {
      title: 'Life Manager',
      icon: 'material-symbols:dashboard-customize-outline-rounded',
      order: 10,
      hideInMenu: true,
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'infinity-nikki',
    path: '/life/project/infinity-nikki',
    component: 'layout.blank$view.infinity-nikki',
    meta: {
      title: '无限暖暖',
      icon: 'material-symbols:stadia-controller-outline-rounded',
      order: 12,
      hideInMenu: true,
      i18nKey: 'route.infinity-nikki'
    }
  },
  {
    name: 'infinity-nikki-manage',
    path: '/life/project/infinity-nikki/manage',
    component: 'layout.blank$view.infinity-nikki-manage',
    meta: {
      title: '无限暖暖管理',
      icon: 'material-symbols:settings-outline-rounded',
      hideInMenu: true,
      activeMenu: 'infinity-nikki',
      i18nKey: 'route.infinity-nikki-manage'
    }
  },
  {
    name: 'japan-travel',
    path: '/life/project/japan-travel',
    component: 'layout.blank$view.japan-travel',
    meta: {
      title: '日本旅行 2026',
      icon: 'material-symbols:flight-takeoff-rounded',
      order: 13,
      hideInMenu: true,
      i18nKey: 'route.japan-travel'
    }
  },
  {
    name: 'japan-travel-manage',
    path: '/life/project/japan-travel/manage',
    component: 'layout.blank$view.japan-travel-manage',
    meta: {
      title: '日本旅行管理',
      icon: 'material-symbols:travel-explore-rounded',
      hideInMenu: true,
      activeMenu: 'japan-travel',
      i18nKey: 'route.japan-travel-manage'
    }
  },
  {
    name: 'projects',
    path: '/life/projects',
    component: 'layout.blank$view.projects',
    meta: {
      title: '项目管理',
      icon: 'material-symbols:folder-outline-rounded',
      order: 11,
      hideInMenu: true,
      i18nKey: 'route.projects'
    }
  }
];
